
version: 2

sources:
    - name: staging
      #For bigquery:
      database: de-zoomcamp-355322


      schema: trips_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: nyc_trips
 